#!/bin/sh


/bin/echo "// Code generated by comment/github.go DO NOT EDIT." > github_token.go
/bin/echo "package comment" >> github_token.go
/bin/echo "const githubToken = \"${GITHUB_TOKEN}\"" >> github_token.go