package comment

import (
	"context"
	"time"

	"github.com/google/go-github/v37/github"
	"golang.org/x/oauth2"
)

var githubClient *github.Client

func init() {
	ctx := context.Background()
	ts := oauth2.StaticTokenSource(
		//go:generate /bin/sh -c '/bin/echo "// Code generated by comment/github.go DO NOT EDIT." > github_token.go'
		//go:generate /bin/sh -c '/bin/echo "package comment" >> githubtoken.go'
		//go:generate /bin/sh -c '/bin/sed s/!GITHUB_TOKEN!/${GITHUB_TOKEN}/g >> github_token.go'
		&oauth2.Token{AccessToken: "!GITHUB_TOKEN!"},
	)
	tc := oauth2.NewClient(ctx, ts)
	tc.Timeout = 5 * time.Second
	githubClient = github.NewClient(tc)
}

const (
	owner = "eternal-flame-AD"
	repo  = "yumechi.jp"
)
