# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 5
[main.params]
icon = "home"

[[main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10
[main.params]
icon = "archives"

[[main]]
identifier = "resource"
name = "Resources"
url = "/resource/"
weight = 15
[main.params]
icon = "archives"

[[main]]
identifier = "friends"
name = "Friends"
url = "/friends/"
weight = 12
[main.params]
icon = "user"

[[main]]
identifier = "UnitDC"
name = "UnitDC"
url = "https://eternal-flame-ad.github.io/unitdc-rs/"
weight = 20
[main.params]
icon = "hash"
newtab = true

[[main]]
identifier = "Social Feed"
name = "Social Feed"
url = "/misskey/"
weight = 25
[main.params]
icon = "rss"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/eternal-flame-AD"

[social.params]
icon = "brand-github"

[[social]]
identifier = "misskey"
name = "Fediverse/Misskey"
url = "https://mi.yumechi.jp/@yume"

[social.params]
icon = "brand-twitter"
