
[build]

  base = "/"

  publish = "public/"

  # Default build command.
  command = "make download-hugo && make build"

  # Directory with the serverless functions, including background functions,
  # to deploy to AWS. This is relative to the base directory if one has been set, 
  # or the root directory if a base has not been set.
  # functions = "functions/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Content-Security-Policy = "frame-ancestors https://www.facebook.com"

    # Multi-value headers are expressed with multi-line strings.
	# cache-control = '''
	# max-age=0,
	# no-cache,
	# no-store,
	# must-revalidate'''

    # Basic-Auth allows you to password protect your whole site.
    # This feature may not be available on all plans.
    # Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"


# redirect japanese users to /ja/
[[redirects]]
  from = "/"
  to = "/ja/"
  status = 302
  force = false
  conditions = {Language = ["ja"]}

# default to /en/
[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = false
